driver:
  name: docker
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "true") %>

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: debian-8.0
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.6
    run_list:
      - recipe[yum-epel]
  - name: centos-7.1
    run_list:
      - recipe[yum-epel]
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[monit]
  - name: source
    run_list:
      - recipe[monit]
    attributes:
      monit:
        source_install: true
  - name: binary
    run_list:
      - recipe[monit]
    attributes:
      monit:
        binary_install: true
