language: ruby
bundler_args: --jobs 4 --retry 3 --without integration
rvm:
- 2.0
- 2.1
- 2.2
script:
- bundle exec rake rubocop
- bundle exec rake foodcritic
- bundle exec rake chefspec
- bundle exec rake kitchen:all
env:
  matrix:
  - CHEF_VERSION: "11.18.6"
  - CHEF_VERSION: "12.0.0"
  - CHEF_VERSION: "12.1.0"
  - CHEF_VERSION: "12.2.0"
  - CHEF_VERSION: "12.3.0"
sudo: false
cache: bundler
